### ISSUE TITLE
Docker image not found

### ISSUE THREAD

**Issue by cv** [sorenmat/k8s-rds#21]
Hi!

I've been trying to follow the installation steps in the README and just bumped into this:

```
$ docker pull sorenmat/k8s-rds
Using default tag: latest
Error response from daemon: manifest for sorenmat/k8s-rds:latest not found
```

Looks like the image isn't being uploaded by Travis?

PS: Thank you so much for `k8s-rds`. It's *exactly* what we've been looking for!

**Comment by sorenmat** [comment]
Thank you for reporting the issue :)
