### ISSUE TITLE
Missing required field CreateDBSubnetGroupInput.SubnetIds

### ISSUE THREAD

**Issue by cv** [sorenmat/k8s-rds#23]
I have created a database following the instructions in the README, and it looks like it has been successful:

```bash
# kubectl apply -f https://raw.githubusercontent.com/sorenmat/k8s-rds/master/db.yaml
secret "mysecret" created
database "mypgsql" created
```

```yaml
# kubectl get database mypgsql -o yaml
apiVersion: k8s.io/v1
kind: Database
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"k8s.io/v1","kind":"Database","metadata":{"annotations":{},"name":"mypgsql","namespace":"default"},"spec":{"class":"db.t2.medium","dbname":"thepgsql","engine":"postgres","name":"thatpgsql","password":{"key":"mykey","name":"mysecret"},"size":10,"username":"postgres"}}
  clusterName: ""
  creationTimestamp: 2018-03-30T00:36:18Z
  generation: 0
  name: mypgsql
  namespace: default
  resourceVersion: "965728"
  selfLink: /apis/k8s.io/v1/namespaces/default/databases/mypgsql
  uid: 5c6d05ff-33b2-11e8-a45f-12df4130596a
spec:
  class: db.t2.medium
  dbname: thepgsql
  engine: postgres
  password:
    key: mykey
    name: mysecret
  size: 10
  username: postgres
status:
  message: Created
  state: Created
```

However, I see this in the logs:

```
# kubectl logs -lname=k8s-rds
2018/03/30 00:37:39 Starting k8s-rds
2018/03/30 00:37:39 Watching for database changes...
2018/03/30 00:37:39 Database CRD status updated
2018/03/30 00:37:39 Seems like we are running in a Kubernetes cluster!!
2018/03/30 00:37:39 Found node with ID:  i-04bed3bea340496f1
2018/03/30 00:37:39 Found the follwing subnets: 
2018/03/30 00:37:39 Seems like we are running in a Kubernetes cluster!!
2018/03/30 00:37:39 Trying to find the correct subnets
2018/03/30 00:37:40 CreateDBSubnetGroup: InvalidParameter: 1 validation error(s) found.
- missing required field, CreateDBSubnetGroupInput.SubnetIds.

2018/03/30 00:37:40 Creating service 'mypgsql' for 
2018/03/30 00:37:40 Creation of database mypgsql done
```

…and no indication as to how to fix it, or how to access that database from within one of my pods. I'm running the latest server version (1.9.3) available through [kops](https://github.com/kubernetes/kops), and I didn't change the default networking configuration in it, which reads:

```yaml
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

Any thoughts would be greatly appreciated.

**Comment by sorenmat** [comment]
Thank you for the detailed issue, there are some issues here :(

1. The first one that spots my eye is `Found the follwing subnets` this means that we weren't able to locate subnets in which we can create the database.

2. The second issue is that it reports back the state created which is a lie :(

I not to much into how kops works, but it seem like your subnets are public, which means that you need to add `publicaccess` to the datbase spec.

I will create a PR that will be more verbose in the output regarding subnets, maybe that will also help.

**Comment by sorenmat** [comment]
See #25

**Comment by genehand** [comment]
I ran into the same issue and noticed it didn't hit the `Found VPC` block either.  Traced it back to https://github.com/sorenmat/k8s-rds/blob/master/main.go#L69 since we're in us-east-1 😄

**Comment by sorenmat** [comment]
@genehand I should fire myself :)
I've created https://github.com/sorenmat/k8s-rds/pull/27 to fix the issue

**Comment by sorenmat** [comment]
This should have been fixed, closing
