### ISSUE TITLE
feature-request: create configmap with rds url and credentials after rds instance has been created

### ISSUE THREAD

**Issue by HerrmannHinz** [sorenmat/k8s-rds#32]
hallo 

i wonder how hard it would be to create some kind of referenceable object which contains the url to the rds instance. and also maybe the credentials. 

would be nice to be able to use those in the deployment of a eg. backend service which will consume the rds instance. some kind of aws rds service broker. 

this could be done via configMaps i assume? 

currently you are just creating the instances. but there is no chance to figure out the rds instance url programatically, right? 

you might get the idea.

**Comment by HerrmannHinz** [comment]
ahhh it seems like you are creating a service already? 

https://github.com/sorenmat/k8s-rds/blob/master/kube/service.go

but why is the service name hardcoded? =)

**Comment by sorenmat** [comment]
It's not the service name that is hardcoded it's the portname :)

You should be able to query the secret from the Kubernetes API, to get the username and password. Depends of you cluster security of cause :)
And as you found out yourself, we do create a service so you can access the database from within the cluster using the name of it.

I will close this one, as I don't think we have any outstanding issues?
Feel free to re-open or create a new one if you disagree :)
