### ISSUE TITLE
go build breaks

### ISSUE THREAD

**Issue by kshafiee** [sorenmat/k8s-rds#36]
Is this a known issue?
<img width="1167" alt="screen shot 2018-09-28 at 5 58 52 pm" src="https://user-images.githubusercontent.com/7294758/46239074-51aaa680-c348-11e8-9f37-460186fc98d9.png">

**Comment by kshafiee** [comment]
@sorenmat

**Comment by sorenmat** [comment]
it seems like the build on master is green https://travis-ci.org/sorenmat/k8s-rds/builds/426651707
But will look more into it.

**Comment by nwillems** [comment]
It seems the repo is not cloned into the right parts of the `$GOPATH`.

Have you tried putting it in `${GOPATH}/src/github.com/k8s-rds`? Hope this helps :-)
