### ISSUE TITLE
unable to create a client for EC2

### ISSUE THREAD

**Issue by CrusaderX** [sorenmat/k8s-rds#38]
Does anybody know the reason of this error?

Kubernetes cluster version: `v1.10.6`
Provider: AWS

Full log:

```
2018/11/06 13:54:05 Starting k8s-rds
2018/11/06 13:54:09 Seems like we are running in a Kubernetes cluster!!
2018/11/06 13:54:09 unable to create a client for EC2
```

**Comment by sorenmat** [comment]
That is not the greatest error message, I've made a change so it now reports back the actual error message it get's from EC2. Let's see if that can help with the problem.
The new change is in docker image `sorenmat/k8s-rds:167`
PR wih fix: https://github.com/sorenmat/k8s-rds/pull/39

**Comment by CrusaderX** [comment]
Yeah, thanks a lot. The error was about rbac permissions

**Comment by sorenmat** [comment]
Cool, closing this one then. Let me know if you're facing anymore issues
