### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by pierreozoux** [sorenmat/k8s-rds#44]
And is it a personal project, or used in a professional context?

It looks nice, and trying to understand the level of effort that will be put there later on.
If I use it, I'll obviously help you then. (But it is not clear yet the direction we are taking in our company).

Basically, we need to provide RDS to our multitenant openshift cluster, and provide day 2 operation as well.

Thanks for your insight!

**Comment by sorenmat** [comment]
It is used in a professional context, to spawn database in testing, sandbox and production environments.
So I hope you can find it useful too, that way we can begin to cover one more use-case :)

**Comment by sorenmat** [comment]
answered, closing :)
