### ISSUE TITLE
Not needed because of aws-servicebroker

### ISSUE THREAD

**Issue by k** [sorenmat/k8s-rds#52]
I think it makes more sense to use the aws curated servicebroker for this purpose https://github.com/awslabs/aws-servicebroker

**Comment by sorenmat** [comment]
If you wanna tie you configuration into AWS, that is one way to go. The reason for this project is that you can run the same configuration (YAML) in different environment.
So if you run it minikube you get a postgres docker image as you database, and if you run it on AWS you get and RDS.
You don't get that abstraction with the service brokers.
