### ISSUE TITLE
Unable to create the databases...

### ISSUE THREAD

**Issue by phanimullapudi** [sorenmat/k8s-rds#69]
I have ensured i have created AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. I am not seeing any errors in the setup. It shows databases is available - but creating any DB instance created in the AWS.

` 
pgsql   5s
`

**Comment by sorenmat** [comment]
Not sure I understand what you are writing :|
It shows that the database is available if you do `kubectl get database` but there are nothing in AWS?

**Comment by phanimullapudi** [comment]
Looks some issue with security restrictions....thanks for the help. Closing this for now.
