### ISSUE TITLE
update the github.com/aws/aws-sdk-go-v2 to v0.29.0 from v0.11.0

### ISSUE THREAD

**Issue by liskl** [sorenmat/k8s-rds#80]
this would allow us to utilize the assumeWithWebIdentity for supporting service account roles in eks.

**Comment by liskl** [comment]
i'm illing to try my hand at it personally.

**Comment by sorenmat** [comment]
Awesome, looking forward to it :)
Let me know if you need any help

**Comment by liskl** [comment]
#89 should help resolve the ability to use assumeRoleWithWebIdentity in the future.

**Comment by liskl** [comment]
@sorenmat sorry it took so long to accomplish, been time constrained for a bit now.
